name: Lint workflow

on:
  pull_request:
    branches:
      - develop
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        - name: Use Node.js 21.x
       - name: Install dependencies
        run: npm install
      - name: Lint with ESLint
